# Autograd with tensors

In [2]:
import torch

In [3]:
w = torch.randn(4,3, requires_grad=True)

In [4]:
y = torch.exp(w)

In [5]:
y

tensor([[0.3229, 0.4264, 0.9813],
        [5.2000, 0.8816, 0.0714],
        [0.5722, 0.7736, 1.9026],
        [3.2237, 0.9905, 0.5815]], grad_fn=<ExpBackward>)

In [8]:
print(y.grad_fn)

In [10]:
outp = y.mean()
print(outp)

tensor(1.3273, grad_fn=<MeanBackward0>)


In [11]:
print(w.grad)

None


In [12]:
outp.backward()

In [13]:
print(w.grad)

tensor([[0.0269, 0.0355, 0.0818],
        [0.4333, 0.0735, 0.0059],
        [0.0477, 0.0645, 0.1586],
        [0.2686, 0.0825, 0.0485]])


In [14]:
print(w.detach())

tensor([[-1.1305, -0.8523, -0.0189],
        [ 1.6486, -0.1260, -2.6396],
        [-0.5582, -0.2567,  0.6432],
        [ 1.1705, -0.0096, -0.5422]])


In [17]:
with torch.no_grad():
    outp - (w+y).mean()
print(outp.requires_grad)

True
