# Tensors 

In [2]:
import torch

In [3]:
## zeros()
w = torch.zeros(4,3)

In [4]:
w.size()

torch.Size([4, 3])

## size() and shape

In [5]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [7]:
w = torch.randn(4,3)
w

tensor([[ 1.3178,  0.5578,  0.7739],
        [-0.5338, -0.8700, -0.8359],
        [-0.4803,  2.6798, -0.4414],
        [ 0.1098, -0.0569, -0.3804]])

In [8]:
t = torch.randn_like(w)
t

tensor([[ 0.1050,  0.9530,  0.4627],
        [ 1.3056,  0.6939,  0.7064],
        [-0.9131, -0.7951, -0.6855],
        [-1.0356, -0.4640,  0.6979]])

## fill_()

In [10]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [12]:
w.view(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [14]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)